### ISSUE TITLE
Limpeza do projeto

### ISSUE THREAD

**Issue by DevSouza** [DevSouza/consulta-cep#1]
Clone o projeto e crie uma ramificação (branch) chamada ```limpando-projeto``` e faca as seguinte alterações  

### Remover arquivos

**App.css**
**App.test.js**
**Index.css**
**logo.svg**
**serviceWorker.js**
**setupTests.js**

No arquivo **App.js** remova os importes da **logo.svg** e **App.css**, altere o retorno da função App para retornar ```<h1>Bem-vindo</h1>```.
  
No arquivo **index.js** remova o importes da **serviceWorker** e **index.css**, remova o seguinte trecho de codigo 
```
// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

### Comandos 
git clone LINK_DO_REPO
git checkout -b NOME-DA-BRANCH

**Comment by Debora7376** [comment]
Demanda Finalizada
